# This is a configuration file for the Github Pages edition of a book by Chastity.
# This site is managed by Chastity White Rose, the Vegan Virgin.

title: The Story of Chad
description: A man who Changed the Heart of Podunk
